app:
  project_name: Cars
  domain: /domain
  version: /api/v1
  debug: False
  allow_origins: ["http://localhost:5173"]

uvicorn:
  host: 0.0.0.0
  port: 8088

db:
  driver: asyncpg
  type: postgresql
  host: db
  port: 5432
  user: postgres
  password: changethis
  name: app
  pool_size: 500
  max_overflow: 50

jwt:
  secret_key: DNhjxI6PnbUumgWBIdSrvAutME3TKV9BmyOuv1u-GPhetL_OEyLYzkW-bwS-RJQrjPsMo9s8TO2XLeJ22Ds46w
  algorithm: HS256
  access_token_ttl: 1800
  refresh_token_ttl: 2592000
  email_token_ttl: 86400
  invite_token_ttl: 86400

smtp:
  tls: True
  host: smtp.gmail.com
  port: 587
  user: vasilsemen04@gmail.com
  password: ukrk rieh ceqv dljs

redis:
  name: redis
  host: redis
  port: 6480
  cache_ttl: 60
