reg_broker_tags = ["Регистрация | Брокер"]
log_broker_tags = [ "Авторизация | Брокер"]
reg_user_tags = ["Регистрация | Пользователь"]
log_user_tags = ["Авторизация | Пользователь"]
log_broker_user_tags = ["Авторизация | Пользователь / Брокер"]
reg_broker_user_tags = ["Регистрация | Пользователь / Брокер"]