"""delete cascade user_permissions

Revision ID: fd1dab19a52b
Revises: 7c75b52e0d67
Create Date: 2025-07-14 18:05:13.155275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd1dab19a52b'
down_revision: Union[str, None] = '7c75b52e0d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_permissions_broker_account_id_fkey'), 'user_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_permissions', 'broker_service_accounts', ['broker_account_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('user_permissions_broker_account_id_fkey'), 'user_permissions', 'broker_service_accounts', ['broker_account_id'], ['id'], onupdate='CASCADE')
    # ### end Alembic commands ###
