"""broker_service_accounts

Revision ID: 4c41f44169a2
Revises: 60b441729123
Create Date: 2025-07-08 17:01:23.210941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c41f44169a2'
down_revision: Union[str, None] = '60b441729123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_service_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['users.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'service_id')
    )
    op.create_index(op.f('ix_broker_service_accounts_broker_id'), 'broker_service_accounts', ['broker_id'], unique=False)
    op.create_index(op.f('ix_broker_service_accounts_id'), 'broker_service_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_broker_service_accounts_login'), 'broker_service_accounts', ['login'], unique=False)
    op.create_index(op.f('ix_broker_service_accounts_password'), 'broker_service_accounts', ['password'], unique=False)
    op.create_index(op.f('ix_broker_service_accounts_service_id'), 'broker_service_accounts', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_service_accounts_service_id'), table_name='broker_service_accounts')
    op.drop_index(op.f('ix_broker_service_accounts_password'), table_name='broker_service_accounts')
    op.drop_index(op.f('ix_broker_service_accounts_login'), table_name='broker_service_accounts')
    op.drop_index(op.f('ix_broker_service_accounts_id'), table_name='broker_service_accounts')
    op.drop_index(op.f('ix_broker_service_accounts_broker_id'), table_name='broker_service_accounts')
    op.drop_table('broker_service_accounts')
    # ### end Alembic commands ###
