"""

Revision ID: 52757d0888aa
Revises: 00471da6d70a
Create Date: 2025-06-27 19:47:37.839217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52757d0888aa'
down_revision: Union[str, None] = '00471da6d70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE \"UserRole\" ADD VALUE 'ADMIN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE \"UserRole\" DROP VALUE 'ADMIN'")
    # ### end Alembic commands ###
