"""broker

Revision ID: 62cb69e2140c
Revises: 993f48ebda16
Create Date: 2025-06-09 17:17:54.004591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cb69e2140c'
down_revision: Union[str, None] = '993f48ebda16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_email'), 'broker', ['email'], unique=True)
    op.create_index(op.f('ix_broker_first_name'), 'broker', ['first_name'], unique=False)
    op.create_index(op.f('ix_broker_id'), 'broker', ['id'], unique=False)
    op.create_index(op.f('ix_broker_last_name'), 'broker', ['last_name'], unique=False)
    op.create_index(op.f('ix_broker_tel'), 'broker', ['tel'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_tel'), table_name='broker')
    op.drop_index(op.f('ix_broker_last_name'), table_name='broker')
    op.drop_index(op.f('ix_broker_id'), table_name='broker')
    op.drop_index(op.f('ix_broker_first_name'), table_name='broker')
    op.drop_index(op.f('ix_broker_email'), table_name='broker')
    op.drop_table('broker')
    # ### end Alembic commands ###
