version: 1
disable_existing_loggers: False
formatters: {
    "default": {
        "format": "[%(name)s] - %(asctime)s - %(levelname)s - %(message)s",
        "datefmt": "%Y-%m-%d %H:%M:%S",
    }
}
handlers: {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "default",
        "level": "INFO",
    }
}
root: {
    "handlers": ["console"],
    "level": "INFO",
}